name: CI (Main)

on:
  push:
    branches-ignore:
      - root

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1

        with:
          version: 1.11

      - name: Gradle (Build)
        run: sh gradlew build

      - name: Copy Artifacts
        run: |
          cp */build/libs/*.jar build/libs

      - name: Upload artifacts (JARs)
        uses: actions/upload-artifact@v2

        with:
          name: JARs
          path: build/libs/*.jar
