name: Publish

on:
  push:
    branches-ignore:
      - root

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Java task hasn't updated for the deprecation yet
        run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v1.0.0

        with:
          version: 1.14

      - name: Set up Gradle properties
        run: |
          mkdir -p ~/.gradle
          echo "githubToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.gradle/gradle.properties

      - name: Gradle (Build)
        run: sh gradlew build

      - name: Gradle (Publish)
        run: sh gradlew -Pkotdis.user=${{ secrets.MAVEN_USER }} -Pkotdis.password=${{ secrets.MAVEN_PASSWORD }} publish

      - name: Copy Artifacts
        run: |
          rm build/libs/*.jar
          cp */build/libs/*.jar build/libs

      - name: Upload artifacts (JARs)
        uses: actions/upload-artifact@v2

        with:
          name: JARs
          path: build/libs/*.jar
