name: CI (Root)

on:
  push:
    branches:
      - root

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1

        with:
          version: 1.11

      - uses: actions/checkout@v1

      - name: Set up Gradle properties
        run: |
          mkdir -p ~/.gradle
          echo "githubToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.gradle/gradle.properties

      - name: Gradle (Build)
        run: sh gradlew build

      - name: Copy Artifacts
        run: |
          rm build/libs/*.jar
          cp */build/libs/*.jar build/libs

      - name: Upload artifacts (JARs)
        uses: actions/upload-artifact@v2

        with:
          name: JARs
          path: build/libs/*.jar
